<a href="https://colab.research.google.com/github/GITSangWoo/BigDataTest/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0%EC%97%B0%EC%8A%B5_1_(%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EC%B4%88).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#연산자

##산술연산자


In [ ]:
print(7+4) #더하기

11


In [ ]:
print(7/4) #나누기

1.75


In [ ]:
print(7%4) #나머지

3


In [ ]:
print(7//4) #몫

1


In [ ]:
print(7**4) #제곱

2401


##비교연산자

In [ ]:
print(7>4)  #왼쪽에 있는 값이 오른쪽에 있는 값보다 크면 참을 반환하고, 그렇지 않으면 거짓을 반환하는 연산자

True


In [ ]:
print(7<4) #왼쪽에 있는 값이 오른쪽에 있는 값보다 작으면 참을 반환하고, 그렇지 않으면 거짓을 반환하는 연산자

False


In [ ]:
print(7==4) #왼쪽에 있는 값이 오른쪽에 있는 값과 같으면 참을 반환하고, 그렇지 않으면 거짓을 반환하는 연산자

False


In [ ]:
print(7!=4) #왼쪽에 있는 값이 오른쪽에 있는 값과 다르면 참을 반환하고, 그렇지 않으면 거짓을 반환하는 연산자

True


##논리 연산자

In [ ]:
True and False #두 개의 논릿값이 모두 참이면 참을 반환하고, 그렇지 않으면 거짓을 반환하는 연산자

False

In [ ]:
True or False  #두 개의 논릿값 중 하나라도 참이면 참을 반환하고, 그렇지 않으면 거짓을 반환하는 연산자

True

In [ ]:
not True       #반대 논릿값을 반환하는 연산자

False

##대입 연산자
---
= : 왼쪽변수에 오른쪽의 값을 대입하는 연산자  
(+,-,x,/,%,**,//)= : 왼쪽의 변수에 오른쪽의 값을  
(더하기,빼기,곱하기,나누기,나머지,제곱,몫)구한 후, 그 결과값을 왼쪽의 변수에 대입하는 연산자   


#변수

## 변수 생성
---
변수를 선언하고 값을 할당할 대는 대입 연산자를 사용한다

In [ ]:
a = "bigdata"

In [ ]:
b=5

In [ ]:
print(a)

bigdata


In [ ]:
print(b)

5


# 자료형
---
자료형은 프로그래밍 언어에서 실수형, 문자형과 같은 여러 종류의 데이터를 식별하는 형태

## 기본 자료형
---


*   기본 자료형은 직접 자료를 표현하는 자료형이다.
*   기본 자료형에는 숫자형, 논리형이 있다.



In [ ]:
print(31+2.7)

33.7


In [ ]:
print(True)

True


## 컬렉션 자료형
---
*   컬렉션 자료형은 시퀀스 자료형과 비시퀀스 자료형이 있다.  
    (시퀀스 자료형은 순서가 있는 자료형, 비시퀀스 자료형은 순서가 없는 자료형)
*   시퀀스 자료형은 문자열형, 리스트형, 튜플형이 있다.   
*   비시퀀스 자료형은 세트형 딕셔너리형이 있다.
---
시퀀스 자료형  
* 문자열형(string): 문자를 한 개 또는 여러개 저장하고자 할 때 사용하는 자료형  
예: s = "soojebi"
* 리스트형(List): 크기가 가변적으로 변하는 선형리스트의 성질을 가지고 있는 자료형  
예:  I =[1,2,3]  
(읽기, 쓰기가 모두 가능)
*튜플형(Tuple): 초기에 선언된 값에서 값을 생성. 삭제, 수정할 수 있는 형태의 자료형  
예: t=(1,2,3)  
(읽기 전용이며 속도가 빠름)
---
비시퀀스 자료형  
*   세트형(set): 중복된 원소를 허용하지 않는 집합의 성질을 가지고 없는 자료형   
예:  s={1,2,3}
*   딕셔너리형(Dictionary) : 키와 값으로 구성된 객체를 저장하는 구조로 되어 있는 자료형   
예: d={'s':1,'j':2,'b':3}



###시퀀스 자료형

#####문자열형(String)

In [ ]:
print("soojebi")

soojebi


In [ ]:
print("Soojebi","World")

Soojebi World


In [ ]:
print("Soojebi"*3)

SoojebiSoojebiSoojebi


####리스트형(List)
---
리스트형 메서드


*   append(x) : 리스트 마지막 요소 뒤에 x값을 추가하는 메서드
*   clear(): 리스트의 모든 항목을 삭제시키는 메서드
*   copy():리스트를 복사하는 메서드
*   count(x) 리스트에서 x항목의 갯수를 알려주는 메서드
*   extend(i):리스트마지막에 컬렉션 자료형 i를 추가하는 메서드
*   index(x): 값 x와 같은 값을  가지고 있는 인덱스 번호를 알려주는 메서드
*   insert(i,x): 리스트 i 번지 위치에 값 x를 삽입하는 메서드
*   pop(): 마지막 항목을 삭제하고 값을 꺼내오는 메서드
*   remove(x): 리스트에서 해당하는 값x를 제거하는 메서드   
    (해당하는 값이 여러개 있을 경우 가장 앞에 있는 값을 제거)
*   reverse(): 리스트의 위치를 전부 역순으로 바꿔주는 메서드
*   sort(): 리스트의 항목들을 정렬하는 메서드



In [ ]:
a=[20,10,30]

In [ ]:
print(a)

[20, 10, 30]


In [ ]:
a.extend(a)

In [ ]:
print(a)

[20, 10, 30, 20, 10, 30]


In [ ]:
a.pop()

30

In [ ]:
print(a)

[20, 10, 30, 20, 10]


In [ ]:
a.reverse()

In [ ]:
print(a)

[10, 20, 30, 10, 20]


In [ ]:
l=[3,5,7]

In [ ]:
l.append(3)

In [ ]:
print(l)

[3, 5, 7, 3]


In [ ]:
l.insert(2,4)

In [ ]:
print(l)

[3, 5, 4, 7, 3]


In [ ]:
l.remove(3)

In [ ]:
print(l)

[5, 4, 7, 3]


####튜플형(Tuple)

In [ ]:
t=('s','j','b')

In [ ]:
print(t)

('s', 'j', 'b')


###시퀀스 자료형 요소 접근 방법

#### 인덱싱

In [ ]:
print("soojebi"[3])

j


In [ ]:
print("soojebi"[-7])

s


In [ ]:
str="soojebi"

In [ ]:
print(str[1])

o


In [ ]:
t=('s','j','b')

In [ ]:
print(t[0])

s


#### 슬라이싱
---


*   슬라이싱은 시퀀스 자료형에서 여러 개의 데이터에 동시에 접근하는 기법이다.
*   시퀀스변수명[시작:종료:스텝]



#####문자열 슬라이싱

In [ ]:
print("soojebi"[1:])

oojebi


In [ ]:
print("soojebi"[2:4])

oj


In [ ]:
print("soojebi"[:3])

soo


#####리스트 슬라이싱

In [ ]:
a=[4,2,7,3,5]

In [ ]:
print(a[0:4:2])

[4, 7]


#####튜플 슬라이싱

In [ ]:
t= ('s','j','b')

In [ ]:
print(t[1:])

('j', 'b')


###비시퀀스 자료형

####세트(Set)형
---

1.   세트형 개념

 *   세트형은 중복된 원소를 허용하지 않는 집합의 성질을 가지고 있는 자료형이다.
 *   세트명 = set([요소1,요소2, ...])

2.   세트형 메서드
   
 *   add(값) : 값을 1개 추가하는 메서드
 *   update([값1,값2,...]):여러 개의 값을 한꺼번에 추가하는 메서드
 *   remove(값): 특정 값을 제거하는 메서드


In [ ]:
s={1,5,7}

In [ ]:
s.add(3)

In [ ]:
print(s)

{1, 3, 5, 7}


In [ ]:
s.add(5)

In [ ]:
print(s)

{1, 3, 5, 7}


In [ ]:
s.update([1,2,3,4])

In [ ]:
print(s)

{1, 2, 3, 4, 5, 7}


In [ ]:
s.remove(1)

In [ ]:
print(s)

{2, 3, 4, 5, 7}


####딕셔너리
---
딕셔너리형은 키와 값으로 구성된 객체를 저장하는 구조의 자료형  
*   딕셔너리 요소 생성  
딕셔너리명={키1:키값1,키2:키값2,...}  

*   딕셔너리형 요소 변경  
딕셔너리명[키]= 값

*   딕셔너리형 요소 삭제  
del 딕셔너리명[키]



In [ ]:
d={'A':5, 'C':4}

In [ ]:
print(d)

{'A': 5, 'C': 4}


In [ ]:
d['K']=7

In [ ]:
print(d)

{'A': 5, 'C': 4, 'K': 7}


In [ ]:
del d['C']

In [ ]:
d['K']=6

In [ ]:
print(d)

{'A': 5, 'K': 6}


###자료형 함수

####Type함수
---
* 자료형을 확인할 수 있는 함수  
---

자료형의 종류


*   기본자료형

  *   정수형(integer) | <class 'int'>
  *   실수형(floating point) | <class 'float'>
  *   논리형(Logical) | <class 'bool'>


*   컬렉션 자료형

 *   문자열형(String) | <class 'str'>
 *   리스트형(List) | <class 'list'>
 *   튜플형(Tuple) | <class 'tuple'>
 *   딕셔너리형(Dictionary) | <class 'dict'>
 *   세트형(Set) | <class 'set'>



In [ ]:
print(type(31))

<class 'int'>


In [ ]:
print(type(2.7))

<class 'float'>


In [ ]:
print(type(True))

<class 'bool'>


In [ ]:
print(type('Soojebi'))

<class 'str'>


In [ ]:
print(type([1,2,3]))

<class 'list'>


In [ ]:
print(type((1,2,3)))

<class 'tuple'>


In [ ]:
print(type({1,2,3}))

<class 'set'>


In [ ]:
print(type({'s':1, 'j':2, 'b':3}))

<class 'dict'>


####len 함수
---
* len 함수는 컬렉션 자료형의 크기를 계산하는 함수

In [ ]:
print(len('Soojebi'))

7


In [ ]:
print(len([1,2,3]))

3


In [ ]:
print(len((1,2,3)))

3


In [ ]:
print(len({1,2,3}))

3


In [ ]:
print(len({'s':1,'j':2,'b':3}))

3


##객체

###배열
---


*   배열은 동일한 유형의 데이터를 저장하는 자료형이다
*   numpy 패키지의 array 함수로 데이터 배열을 생성한다.




In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],[1,2,3]])

In [ ]:
print(b)

[[1 2 3]
 [1 2 3]]


### 데이터 프레임
---
* 데이터 프레임은 행과 열을 가지는 표형식의 구조로 숫자, 문자 등 다양한 형식의 데이터 저장이 가능한 자료형이다.
* pandas 패키지의 DataFrame 함수로 데이터 프레임을 생선한다.

In [ ]:
import pandas as pd

In [ ]:
d = pd.DataFrame({'a':[1,2,3,4],
                  'b':[2,3,4,5],
                  'e':['M','F','M','F']})

In [ ]:
print(d)

   a  b  e
0  1  2  M
1  2  3  F
2  3  4  M
3  4  5  F


# 조건문 - if 문

##if 문
---
 * if문 조건이 참인지 거짓인지에 따라 경로를 선택하는 명령문이다.
  
---
 * if문 조건이 참일 경우 if안에 있는 명령문을 실행한다.
 * if문의 조건이 거짓이면서 elif 문의 조건이 참일 경우 elif안에 있는 명령문을 실행한다.
 * elif는 여러개 사용이 가능하다.
 * else 는 if문의 조건문이 거짓이고 여러개의 elif 문이 모두 거짓일 때 else 안에 있는 명령문을 실행한다.  
 (else는 사용하지 않거나 한 번만 사용)
---
* if 문 문법   
 ```  
 if 조건문:
    명령문
 elif 조건문:
    명령문
 else:
    명령문
 ```

In [ ]:
score=20

In [ ]:
if score >=90:
  print("A")
elif score >=80:
  print("B")
elif score >= 70:
  print("C")
else:
  print("F")

F


#반복문

## for 문
---
* for문은 in 연산자 뒤에 range 함수를 사용하여 반복의 범위를 지정하거나 리스트 개수만큼 반복을 수행한다.


###(1) 일반 for 문
 * range 함수는 범위를 지정하는 함수이다.
 * range 함수에서 시작을 생략하면 0, 스텝 값을 생략하면 1이 자동으로 들어간다.  
 ```
for 변수 in range(시작, 종료, 스텝):  ## (시작) 값부터 for문을 반복할 때마다                                        
명령문                                ## (스텝) 수만큼값을 증가시키고 변숫값이 (종료) 값 이상이면 반복문을 종료
```
 * range 함수에 값이 하나일 경우 시작=0, 스텝=1이 자동으로 들어가고,
range함수에 값이 두 개 일 경우 스텝= 1이 자동으로 들어간다.

In [ ]:
i=0

In [ ]:
sum=0

In [ ]:
for i in range(1,5):
  sum= sum + i

In [ ]:
print(sum)

10


###(2) for each 문
---
for each 문은 시퀀스 자료형의 각각의 요소가 변수에 대입되어 명령문을 싱행하며 반복한다.  
```  
for 변수 in 시퀀스 자료형:
  명령문

```

In [ ]:
li=[1,2,3,4,5]
for a in li:
  print(a)

1
2
3
4
5


##while 문
---
while문은 반복 횟수의 지정 없이 조건이 참이면 계속해서 반복을 수행하는 반복문이다.  
```
while 조건문:        ##조건문 뒤에는 반드시 콜론(':')을 붙인다.
  명령문

```

In [ ]:
i=0

In [ ]:
sum=0

In [ ]:
while i < 4:
  i=i+1
  sum= sum+i

In [ ]:
print(sum)

10


##루프 제어 명령어
---
반복문에서 무한 루프를 방지하기 위해 break문과 contiune문을 사용한다.

###break문
---
break 문은 반복문을 중간에 탈출하기 위해 사용하는 명령어이다.

In [ ]:
for i in range(1,5):
  print(i)
  if i ==2:
    break

1
2


###contiune 문
---
continue문은 반복문에서 다음 반복으로 넘어갈 수 있도록 하는 명령어이다.

In [ ]:
for i in range(1,5):
  if i == 2 :
    continue
  print(i)

1
3
4


#사용자 정의 함수
---


*   사용자 정의 함수는 사용자가 직접 새로운 함수를 정의하여 사용하는 방법이다.
*   사용자 정의 함수에서 파라미터나 생성된 변수는 사용자 정의 함수가 종료되면 없어진다.
* 사용자 정의 함수 문법
```
def 함수명(변수명, ...):
  명령어
  return 반환값
```


In [ ]:
def fn (num):
  if num % 2 == 0:
    return 'Y'
  else:
    return 'N'

In [ ]:
a= fn(5)

In [ ]:
print(a)

N
